version: '3.8'
services:
  db:
    container_name: POSTGRES_DB
    ports:
      - '5432:5432'
    build:
      context: './docker'
      dockerfile: 'Dockerfile.db'
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB_NAME
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: APP
    ports:
      - '4000:4000'
    build:
      context: '.'
      dockerfile: './docker/Dockerfile.app'
    restart: unless-stopped
    environment:
      - PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - AUTH_USERNAME
      - AUTH_PASSWORD
      - DATABASE_URL
    env_file:
      - ./.env
volumes:
  db-data: